# Generated by Django 3.0.6 on 2020-05-29 15:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cost_down',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='question',
            name='cost_up',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
