# Generated by Django 3.0.6 on 2020-05-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csts', '0002_auto_20200529_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Port',
        ),
    ]
