# Generated by Django 3.0.6 on 2020-06-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csts', '0005_auto_20200601_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportedge',
            name='travel_day',
            field=models.IntegerField(default=1),
        ),
    ]
