# Generated by Django 3.0.6 on 2020-06-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csts', '0007_auto_20200604_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='port',
            options={'verbose_name': 'Порты'},
        ),
    ]
